server:
  port: 80
spring:
  application:
    name: crowd-zuul
  redis:
    host: 127.0.0.1
  session:
    store-type: redis   #spring-session的实现方式为Redis缓存
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  ignored-services: "*"
  sensitive-headers: "*"     # 在Zuul向其他微服务重定向时保持原本头信息（请求头、响应头）
                        # eg: zuul重定向到auth时，其request，response默认重新创建  ，需要写该配置项，改为保持原请求头，来传递信息
  routes:  #自定义路由规则
    portal:  #自定义路由规则名称
      service-id: crowd-auth
      path: /**  # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
    project:
      service-id: crowd-project
      path: /project/**

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000