server:
  port: 5000
spring:
  application:
    name: crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: null
    access-key-secret: null
    bucket-domain: null
    bucket-name: crowd-for-lcc
    end-point: http://oss-cn-shanghai.aliyuncs.com

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
