server:
  port: 1000
spring:
  application:
    name: crowd-eureka
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #标明该eureka工程本身不需要去注册
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/