server:
  port: 4000
spring:
  application:
    name: crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    host: https://dfsns.market.alicloudapi.com
    path: /data/send_sms
    method: POST
    app-code: 24dd7d967f1d4d91bd018492aab11fbb
    sign: null
    skin: TPL_0000


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


